const PLANS = [
  {
    brand: "ドコモ",
    name: "ドコモの小容量向けプラン",
    price: 3850,
    data: 10,
    store: true,
    family: true,
    quality: true,
    senior: true,
    call: "short",
    officialUrl: "https://www.docomo.ne.jp/charge/",
    checkedAt: "2026-07-22"
  },
  {
    brand: "ahamo",
    name: "ahamo",
    price: 2970,
    data: 30,
    store: false,
    family: false,
    quality: true,
    senior: false,
    call: "short",
    officialUrl: "https://ahamo.com/",
    checkedAt: "2026-07-22"
  },
  {
    brand: "au",
    name: "auの大容量向けプラン",
    price: 8008,
    data: 999,
    store: true,
    family: true,
    quality: true,
    senior: true,
    call: "many",
    officialUrl: "https://www.au.com/mobile/charge/",
    checkedAt: "2026-07-22"
  },
  {
    brand: "povo",
    name: "povo2.0",
    price: 2700,
    data: 30,
    store: false,
    family: false,
    quality: true,
    senior: false,
    call: "none",
    officialUrl: "https://povo.jp/",
    checkedAt: "2026-07-22"
  },
  {
    brand: "UQ mobile",
    name: "UQ mobile 中容量プラン",
    price: 3828,
    data: 35,
    store: true,
    family: true,
    quality: true,
    senior: true,
    call: "short",
    officialUrl: "https://www.uqwimax.jp/mobile/plan/",
    checkedAt: "2026-07-22"
  },
  {
    brand: "SoftBank",
    name: "SoftBankの大容量向けプラン",
    price: 7425,
    data: 999,
    store: true,
    family: true,
    quality: true,
    senior: true,
    call: "many",
    officialUrl: "https://www.softbank.jp/mobile/price_plan/",
    checkedAt: "2026-07-22"
  },
  {
    brand: "LINEMO",
    name: "LINEMO ベストプランV",
    price: 2970,
    data: 30,
    store: false,
    family: false,
    quality: true,
    senior: false,
    call: "short",
    officialUrl: "https://www.linemo.jp/plan/",
    checkedAt: "2026-07-22"
  },
  {
    brand: "Y!mobile",
    name: "Y!mobile 中容量プラン",
    price: 4158,
    data: 30,
    store: true,
    family: true,
    quality: true,
    senior: true,
    call: "short",
    officialUrl: "https://www.ymobile.jp/plan/",
    checkedAt: "2026-07-22"
  }
];
